### ISSUE TITLE
Su - per!

### ISSUE THREAD

**Issue by pflegende** [mstoetzer/awesome-dpsg#1]
[![Awesome](https://cdn.jsdelivr.net/gh/sindresorhus/awesome@d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)

also ein cooles Banner ist das schon mal. Und die Idee ist super.

Wann soll'n wir wegen content wieder vorbeischauen?

In Erfurt haben wir ja mit Dr. Neymeyr einen begeisterten Altpfadfinder. Wir basteln gerade an einer Inventur intergenerationeller Projekte insbesondere zur digitalen Teilhabe. Da würde auch infrastruktur- und software-tool- seitig noch jede Hand gebraucht.

Wenn Ihr also von den Erfurter Pfadfindern jemand kennt: Schickt Sie bei uns vorbei. Die IT-Nerds treffen sich Mittwochs ab 18 Uhr im Bytespeicher (Liebknechtstr. 8) https://status.bytespeicher.org

CU

**Comment by mstoetzer** [comment]
Hi @pflegende, füge sehr gerne Einträge via PR hinzu. Diskussionen über Themen etc gerne via Discussions in diesem Projekt. Die Struktur wird sich mit der Zeit ergeben. Als Orientierung und Inspiration können andere awesome listen auf GitHub dienen. Grüße
